# global keyword is required to identify the section for all global properties (Req #C3) at the top level.
global:
  # pipeline_name: valid_pipeline
  docker: 
    registry: 'dockerhub'
    image: 'ubuntu:latest'
  artifact_upload_path: 'GitHub.com'

stages: ['build', 'test']

jobs:
    checkout:
        stage: build
        scripts: ['git clone']

    compile:
        stage: build
        allow_failure: True
        needs: ['checkout']
        scripts:
          - 'poetry install'
        artifacts:
            on_success_only: True
            paths:
                - 'build/lib'
    
    pytest:
        stage: test
        scripts: ['poetry run pytest']