# Another valid configuration file that will be called when controller's
# repo is set and cli does not specify repo and yml file by default
# Pipeline name changed to avoid duplication names
global:
    pipeline_name: "cicd_pipeline"
    docker: 
        registry: 'dockerhub'
        image: "sjchin88/python-git-poetry:latest"
    artifact_upload_path: "t4-cicd-cs6510"

# default stages: [build, test, doc, deploy]
stages: ['build', 'test']

jobs:
    # Job for build stage
    checkout:
        stage: build
        scripts: ['git clone https://github.com/sjchin88/cicd-python .']

    compile:
        stage: build
        allow_failure: False
        needs: ['checkout']
        scripts: 
            - 'poetry config virtualenvs.path /app/.cache/pypoetry/virtualenvs'
            - 'poetry install'

    # Job for test stage
    pytest:
        stage: test
        allow_failure: True
        scripts: 
            - 'poetry config virtualenvs.path /app/.cache/pypoetry/virtualenvs'
            - 'poetry run pytest'
        artifacts:
            on_success_only: False
            paths: 
                - 'htmlcov'
    
    pylint:
        stage: test
        scripts: 
            - 'poetry config virtualenvs.path /app/.cache/pypoetry/virtualenvs'
            - 'poetry run pylint ./src --fail-under=9.5'

    
